name = "waiver-system"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "PDF_STORAGE"
bucket_name = "waiver-pdfs"

[[d1_databases]]
binding = "DB"
database_name = "waiver-db"
database_id = "9af8c837-9326-4723-9a5c-f048870aed7e"

[[kv_namespaces]]
binding = "CONFIG"
id = "839815e215af46048bc18e3c886756f0"

[vars]
EMAIL_FROM = "waivers@yourdomain.com"
LEGAL_VERSION = "v1.0"
