name = "waiver-system"
main = "worker.js"
compatibility_date = "2024-09-23"

compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"

[browser]
binding = "BROWSER"

[[send_email]]
name = "SEND_EMAIL"
destination_address_allowlist = ["*"]

[[r2_buckets]]
binding = "PDF_STORAGE"
bucket_name = "waiver-pdfs"

[[d1_databases]]
binding = "DB"
database_name = "waiver-db"
database_id = "9af8c837-9326-4723-9a5c-f048870aed7e"

[vars]
VERSION = "1.0"